/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OjkjLOnMo4c
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { RadioGroupItem, RadioGroup } from "@/components/ui/radio-group"
import { Button } from "@/components/ui/button"

export function PayOptionThree() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100 px-4 py-6 dark:bg-gray-950">
      <div className="w-full max-w-md rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800">
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold">Make Payment</h1>
            <div className="flex items-center gap-2">
              <LockIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
              <span className="text-sm text-gray-500 dark:text-gray-400">Secure</span>
            </div>
          </div>
          <div className="grid gap-4">
            <div className="space-y-2">
              <Label htmlFor="card-number">Card Number</Label>
              <Input className="w-full" id="card-number" placeholder="1234 5678 9012 3456" type="text" />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="expiry-date">Expiry Date</Label>
                <div className="flex items-center gap-2">
                  <Select>
                    <SelectTrigger className="w-full">
                      <SelectValue placeholder="MM" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="01">01</SelectItem>
                      <SelectItem value="02">02</SelectItem>
                      <SelectItem value="03">03</SelectItem>
                      <SelectItem value="04">04</SelectItem>
                      <SelectItem value="05">05</SelectItem>
                      <SelectItem value="06">06</SelectItem>
                      <SelectItem value="07">07</SelectItem>
                      <SelectItem value="08">08</SelectItem>
                      <SelectItem value="09">09</SelectItem>
                      <SelectItem value="10">10</SelectItem>
                      <SelectItem value="11">11</SelectItem>
                      <SelectItem value="12">12</SelectItem>
                    </SelectContent>
                  </Select>
                  <span className="text-gray-500 dark:text-gray-400">/</span>
                  <Select>
                    <SelectTrigger className="w-full">
                      <SelectValue placeholder="YY" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="23">23</SelectItem>
                      <SelectItem value="24">24</SelectItem>
                      <SelectItem value="25">25</SelectItem>
                      <SelectItem value="26">26</SelectItem>
                      <SelectItem value="27">27</SelectItem>
                      <SelectItem value="28">28</SelectItem>
                      <SelectItem value="29">29</SelectItem>
                      <SelectItem value="30">30</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="cvc">CVC</Label>
                <Input className="w-full" id="cvc" placeholder="123" type="text" />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="amount">Amount</Label>
              <RadioGroup className="grid grid-cols-2 gap-2" defaultValue="100">
                <Label
                  className="flex cursor-pointer items-center justify-between rounded-md border border-gray-200 bg-white p-4 text-gray-900 transition-colors hover:bg-gray-100 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:hover:bg-gray-800 dark:border-gray-800"
                  htmlFor="amount-50"
                >
                  <RadioGroupItem id="amount-50" value="50" />
                  <span>R50</span>
                </Label>
                <Label
                  className="flex cursor-pointer items-center justify-between rounded-md border border-gray-200 bg-white p-4 text-gray-900 transition-colors hover:bg-gray-100 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:hover:bg-gray-800 dark:border-gray-800"
                  htmlFor="amount-100"
                >
                  <RadioGroupItem id="amount-100" value="100" />
                  <span>R100</span>
                </Label>
                <Label
                  className="flex cursor-pointer items-center justify-between rounded-md border border-gray-200 bg-white p-4 text-gray-900 transition-colors hover:bg-gray-100 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:hover:bg-gray-800 dark:border-gray-800"
                  htmlFor="amount-200"
                >
                  <RadioGroupItem id="amount-200" value="200" />
                  <span>R200</span>
                </Label>
                <Label
                  className="flex cursor-pointer items-center justify-between rounded-md border border-gray-200 bg-white p-4 text-gray-900 transition-colors hover:bg-gray-100 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:hover:bg-gray-800 dark:border-gray-800"
                  htmlFor="amount-250"
                >
                  <RadioGroupItem id="amount-250" value="250" />
                  <span>R250</span>
                </Label>
              </RadioGroup>
            </div>
          </div>
          <Button className="w-full">Make Payment</Button>
        </div>
      </div>
    </div>
  )
}

function LockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  )
}
