/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/T5hpEoS80zb
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import {
  SelectValue,
  SelectTrigger,
  SelectContent,
  Select,
} from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function PayOptionTwo() {
  return (
    <div className="flex items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <Card className="w-full max-w-md p-6 bg-white rounded-lg shadow-lg dark:bg-gray-800">
        <CardHeader>
          <CardTitle className="text-2xl font-bold">Payment</CardTitle>
          <CardDescription className="text-gray-500 dark:text-gray-400">
            Enter your payment details
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="card-number">Card Number</Label>
            <Input
              id="card-number"
              maxLength={16}
              placeholder="0000 0000 0000 0000"
              required
              type="text"
            />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="expiry-date">Expiry Date</Label>
              <div className="grid grid-cols-2 gap-2">
                <Select name="expiry-month">
                  <SelectTrigger>
                    <SelectValue placeholder="MM" />
                  </SelectTrigger>
                  <SelectContent />
                </Select>
                <Select name="expiry-year">
                  <SelectTrigger>
                    <SelectValue placeholder="YY" />
                  </SelectTrigger>
                  <SelectContent />
                </Select>
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="cvc">CVC</Label>
              <Input
                id="cvc"
                maxLength={3}
                placeholder="123"
                required
                type="text"
              />
            </div>
          </div>
          <div className="space-y-2">
            <Label>Amount</Label>
            <div className="grid grid-cols-2 gap-2">
              <Button variant="outline">R50</Button>
              <Button variant="outline">R100</Button>
              <Button variant="outline">R200</Button>
              <Button variant="outline">R250</Button>
            </div>
          </div>
        </CardContent>
        <CardFooter>
          <Button className="w-full" type="submit">
            Make Payment
          </Button>
        </CardFooter>
      </Card>
    </div>
  )
}
